### ISSUE TITLE
automatic checking if the order has been paid in Django admin panel

### ISSUE THREAD

**Issue by DEENUU1** [DEENUU1/E-COMMERCE-PROJECT-WORKING-ON-#18]

**Comment by m93n** [comment]
do you know signal in django?!
you can use this package for checking automatic and doing sth.

**Comment by DEENUU1** [comment]
Done.
I had trouble testing this on a local server however I used ngrok.
And I disabled the csrf token for cart views because I couldn't use the ngrok server at that time
